### PR TITLE
Added function to request tv show's content-rating.

### PR DESCRIPTION
**Pull request by wagnered**
I'm working on the Ampache project which uses your library.  We want to make Ampache capable of grabbing the TV show's content rating, To accomplish this, the new function (feature) must be added to the library.

I have been using it in my developement branch, but cannot publish it until the function has been added and published in your library.

I hope you will accept this pull requesst and offer this new funtion to the public.

Regards,
Ernie Wagner

### CODE REVIEW

**Comment by wtfzdotnet** [comment]
Hi Ernie,

Thanks for the PR, it needs a little bit more work before I'll merge it in;

- could you please copy the api method description from tmdb into the phpdoc
- could you also add the method into the repository section

A little bit unit testing would have been nice but I can tackle this myself. I'll be back home tonight, and I'll review the PR again.

Thanks,

Michael

**Comment by wagnered** [comment]
Michael,

I am still getting to know the power of php and the git repository, so
your requests are completely new to me, but I will take a somewhat
educated guess:

by "phpdoc", I am assuming that you are referring to the commented
section just above the actual function in tv.php?

And by "repository section" I am assuming you are referring to the file
repository/TvRepository.php?


If the process requires something different or more, I'm at a loss.

As for unit testing, I haven't been exposed to that process at all.

I'll wait for your response before pushing the changes to my remote
fork.

If I remember correctly, one time, I did this with a pull request to
Ampache and git magically took care of updating the pull request on the
upstream branch.

Regards,

-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by wtfzdotnet** [comment]
Hi Ernie,

Your guesses are spot on :+1: , I'll take care of the unit testing of it. 

Yes you can just add commits to the local branch you were working on, and push them the same way you did before, they'll get added to the Pull Request.

Thanks again!

Michael

**Comment by wagnered** [comment]
I have a problem with my email client, Evolution, which stops retrieving
new email but doesn't let me know unless I manually try to retrieve new
items.  So I just received your reply from yesterday.

OK, I pushed the changes to my remote on github.

 Installed phpunit.phar to give it a try and could not get the function
to fail even when deliberately trying, although I did see several
"risky" functions. 

I hope my changes are acceptable, but will make additional changes if
necessary. For Ampache's purpose, with this addition, the php-tmdb-api
library will be complete.

Regards,

Ernie

-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by wtfzdotnet** [comment]
@wagnered I marked out a couple of problems, also the Model and Factory haven't been updated. You can cheat by looking at the Movie Factory and Model which already have the content ratings, I didn't check if the contents of the response are different though.

Would also be nice seeing two examples added as usual.

If you need some help let me know.

**Comment by wtfzdotnet** [comment]
https://github.com/wagnered/php-tmdb-api/commit/adf371a210671ea1f3420f145706695b3b4f9764#commitcomment-9804982 still needs to get fixed, are you willing to update the above or should I just merge your stuff in and take care of it later?

I took a look at the ampache project, but didn't find a quick reference as to where my library is being used? :)

**Comment by wagnered** [comment]
The api exists in modules/Tmdb and is referenced from modules/plugins/Tmdb.plugin.php. It's activates when one want to get metadata/images for catalogs created from designated scanned folders.

 Ampache began before the Controller-Model-View framwwork came into favor so is very difficult (for me) to reverse engineer. Especially where javascript and jQuery is involved.

Anyway, this feature is only on the todo list, not on any milestone yet so no hurry.  I  would like to try updating per your request above, although not knowing the capabilities of unit testing, I'm wondering why the need, so I have a better understanding why I will be making the additions (I enjoy learing).

I will push the change to wagnered@adf371a#commitcomment-9804982 (changing $tvshow_id to $id).

**Comment by wtfzdotnet** [comment]
Without the neccesary changes to the Factory and the Model the Repository side of using this functionality, won't actually function. The method you are calling to  obtain the subresult-set from the Tv model does not exist yet.

The need for unit testing is pretty simple, before I even look at the code you have provided I know in advance it didn't break anything that's tested. It also forces you to write better code :).

I'll be taking a look at it later, thanks again for your efforts!

**Comment by wagnered** [comment]
Once I got the content ratings functions added to the TV factory tests,
the TV repository tests and examples fell quickly into place.

But because I initially had problems with understanding PHPunit and
problems with Eclipse I got my local repository into a weird state and
ended up re-cloning your php-tmdb-api repository before completing the
necessary changes.

I hope I didn't cause a problem with the existing pull request. I will
be happy to submit a new pull request or can I just push the new changes
to my re-cloned fork on github as I did before?


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by wtfzdotnet** [comment]
There's a lot of junk in your last commit ( from phpunit files to ide settings ) please review the diff, https://github.com/wtfzdotnet/php-tmdb-api/commit/c3e09a23f3af358a3cc9a2335794c945c7c9ba0d

You would still have to implement some more stuff, I'll take care of this issue and continue from your previouis commit.

**Comment by wagnered** [comment]
"There's a lot of junk in your last commit ( from phpunit files to ide
settings ) please review the diff, c3e09a2".

Yes, git refused to ignore them even though they were placed into
the .gitignore file.  That is why I re-forked/locally cloned your
php-tmdb-api repository. After re-cloning, the phpunit and other files
are no longer in the commits.  I think that because I re-cloned your
repository, "git diff c3e09a2" cannot be found.

Also, After re-cloning the repository, I believe I added all the changes
you requested.  TVfactoryTests, TVRepositoryTests, Two examples; one in
the examples/tv/api/tv/ sub-folder and one in the examples/tv/models/tv
sub-folder.  So I guess that the fact that I re-cloned your repository
means that I would need to create a new pull request for the new and  (I
believe) complete changes the the api? If there is any more "stuff"
required, the additions would have to be explicitly stated.

The new changes are waiting to be pushed to my github fork.

Well, I enjoyed the learning experience, but it is your call.


Regards and thanks,

-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by wtfzdotnet** [comment]
Hi Ernie,

I didn't mean to discourage you at all, I just rewrote your pull requests history in the `pr-76` branch to remove all the unnecessary files, I'll make sure the test suite is valid, and you can work your way through the errors the test suite returns. I'll give you another heads up when done.

Michael

**Comment by wtfzdotnet** [comment]
Todo list

[ ] Add property and constructor for the `contentRatings`  in `Model/Tv`
[ ] Add an AppendToResponse string to the load method in `Repository/TvRepository`, I have already created a constant for this method.
[ ] Remove extra newline at line 96 in `Repository/TvRepository`
[ ] Add an `Model/Tv/ContentRating` class.
[ ] Add code in the create method in the `Factory/TvFactory`, to populate the data coming from the API, should make use of createGenericCollection and pass it the results array ( see keywords for example ).
[ ] Add an example for the repository bit, `examples/tv/model/tv/content_ratings.php`.

Please take care of only committing what you actually changed :), and keep the current code style in tact.

I'd suggest you branch off the pr-76 branch and continue your work, afterwards create an new pull request against pr-76 again, so it's easier for me to merge changes without affecting the develop branch. if you could submit a pull request asap, I'll copy over the todo to keep things in one place, I'll be closing this pull request ok?

**Comment by wtfzdotnet** [comment]
Also take a look at the comments I made in https://github.com/wtfzdotnet/php-tmdb-api/commit/117d41c5a7b86e761f3021fd4edc04c2c63da8b4

**Comment by wagnered** [comment]
OK for this and to close current PR.
-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Pull request closed without merging**
