### PR TITLE
Seperate TMDB and Engine code.

### PR DESCRIPTION
**Pull request by NMullen**
This "small" change differentiates the two seperate projects that exist in this code base. The Engine (Caching, Logging, HttpClient) integration and the Api Client. 

The benefit to this change is that it now should be easy to extend the engine to implement other APIs. All in theory you would need to do is extend the Engine class as TMDB does.

No changes to unit tests were made.

### CODE REVIEW

**Comment by NMullen** [comment]
I have managed to stuff something up, not sure why I have 3 commits for this change. I an still trying to wrap my head around github. Sorry.

**Comment by wtfzdotnet** [comment]
Could you elaborate a bit why this change should be made? As far as I see it would be weird to include an non-related API library to use the structure I have created, for use in a different API implementation?

If the latter is the case then I oppose this change.

**Comment by wtfzdotnet** [comment]
The only way a change like this would be better, is to separate these parts into two different libraries on github, but I still wonder how useful that will prove to be.

**Comment by NMullen** [comment]
>Could you elaborate a bit why this change should be made? As far as I see it would be weird to include an non-related API library to use the structure I have created, for use in a different API implementation?

The structure you have created, the Engine portion of the code is quite generic. Very little of it is actually TMDB specific. The TMDB api is also quite generic in that a lot of apis follow the same conventions. 

>The only way a change like this would be better, is to separate these parts into two different libraries on github, but I still wonder how useful that will prove to be.

I agree, seperating them into two projects is something I could see happening. The original insperation behind this request was that I also needed to pull data from FanArt.tv. By decoupling the Engine from the implementation of TMDB I could extend just the Engine and create a seperate implementation.

**Comment by wtfzdotnet** [comment]
I'll keep this to a no, I really don't see the use :)

**Pull request closed without merging**
