### PR TITLE
Change Client.php dependency from Monolog to Psr

### PR DESCRIPTION
**Pull request by NMullen**
changing dependency on Monolog to Psr\Log as per composer requirements

### CODE REVIEW

**Comment by wtfzdotnet** [comment]
Quite busy at the moment, thanks for the input, I'll try and review it tonight!

**Comment by wtfzdotnet** [comment]
Thanks, sorry for the delay!

**Comment by NMullen** [comment]
Thanks for accepting!

**Comment by wtfzdotnet** [comment]
Always happy to merge flawless PRS that make sense! :)

**Pull request merged**
